### ISSUE TITLE
Hardware and Learning Cycles 

### ISSUE THREAD

**Issue by ghost** [sparkfun/SparkFun_BQ40Z50_Battery_Manager_Arduino_Library#1]
Hi, do you have schematics for 2s battery pack?

Do you know if the learning cycle is something needed or if we can actually correctly read all the battery parameters without it? 

How can I set the registers for total capacity, number of cells etc?

Thanks

**Comment by nseidle** [comment]
Hello! As the readme states:

> SparkFun does not currently sell a board that has the BQ40Z50 but does have a few products that internally utilize the IC. 

So sorry, no, we don't have any schematics.

>> How can I set the registers for total capacity, number of cells etc?

> we have implemented a handful of functions we need for the products that use the IC. We welcome PRs to expand features that users may want.

So if you'd like to add a feature, please send us a PR! We'd be happy to review it.
